---
- name: web server provisioning playbook
  hosts: all
  remote_user: "{{ ansible_ssh_user }}"

  tasks:
  - name: install packages
    apt:
      force: yes
      pkg: nginx,git,python3,python-pip,python3-pip,python3-setuptools,software-properties-common
    become: yes

  # nginx configuration
  - name: add nginx.conf to /etc/nginx
    become: yes
    template:
      src: ./config/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: add nginx server config to nginx sites-available
    become: yes
    template:
      src: ./config/nginx/webserver.nginx.j2
      dest: /etc/nginx/sites-available/{{ host }}
    notify:
      - restart nginx

  - name: add default config to route http to https
    become: yes
    template:
      src: ./config/nginx/default.nginx.j2
      dest: /etc/nginx/sites-available/default
    notify:
      - restart nginx

  - name: add symlink to nginx sites-enabled
    become: yes
    file:
      src: "/etc/nginx/sites-available/{{ host }}"
      dest: "/etc/nginx/sites-enabled/{{ host }}"
      state: link
    notify:
      - restart nginx

  - name: add symlink to default
    become: yes
    file:
      src: "/etc/nginx/sites-available/default"
      dest: "/etc/nginx/sites-enabled/default"
      state: link
    notify:
      - restart nginx

  - name: add user www-data to run the nginx server
    become: yes
    user:
      name: www-data
      shell: /usr/sbin/nologin
      append: yes

  # Configure gunicorn
  - name: install gunicorn service
    become: yes
    template:
      src: ./config/gunicorn/gunicorn.service.j2
      dest: "/etc/systemd/system/gunicorn-{{ host }}.service"
    notify:
      - restart gunicorn

  - name: make gunicorn start on boot
    become: yes
    service:
      name: "gunicorn-{{ host }}"
      enabled: yes

  - name: add /etc/gunicorn.d
    become: yes
    file:
      path: /etc/gunicorn.d
      state: directory
  
  - name: add gunicorn configuration
    become: yes
    template:
      src: ./config/gunicorn/gunicorn.py.j2
      dest: /etc/gunicorn.d/gunicorn.py

  # Update code and configuration from repository
  - name: download code from repository
    git:
      repo: "{{ repo }}"
      dest: "{{ site_directory }}"
      version: "{{ branch | default('HEAD') }}"
      force: yes

  - name: install virtualenv via pip
    pip:
      name: virtualenv
      executable: pip3

  - name: update Python virtual environment
    become_user: "{{ ansible_ssh_user }}"
    pip:
      virtualenv: "{{ site_directory }}/virtualenv"
      virtualenv_command: /usr/bin/python3.6 -m venv
      requirements: "{{ site_directory }}/requirements.txt"

  - name: add .env config file
    template:
      src: ./config/gunicorn/webserver.env.j2
      dest: "{{ site_directory }}/.env"
    notify:
      - restart gunicorn

  # Install certbot for use with Let's Encrypt
  - name: add certbot apt repository
    become: yes
    apt_repository:
      repo: ppa:certbot/certbot
      state: present

  - name: download certbot packages for use with nginx
    become: yes
    apt:
      force: yes
      pkg: certbot,python-certbot-nginx

  handlers:
  - name: restart nginx
    become: yes
    service:
      name: nginx
      state: restarted

  - name: restart gunicorn
    become: yes
    systemd:
      name: "gunicorn-{{ host }}"
      daemon_reload: yes
      enabled: yes
      state: restarted
...
